# URL to Persona verification server
ASSERT_URL: https://verifier.login.persona.org/verify

# Prefix that will be added to every db created by couch-persona
DB_PREFIX: couch_persona_

# Name of db that will be used to store valid app names
APP_DB: apps

# Name of db that will be used to store developer profiles
DEV_DB: developers
